# Generated by Django 3.2.5 on 2021-11-09 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('imageField', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('nb_answer', models.IntegerField(blank=True, null=True)),
                ('nb_image', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('imageField', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('n_answer', models.IntegerField(blank=True, null=True)),
                ('n_image', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(blank=True, max_length=255, null=True, upload_to='image/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('microscopy', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_type', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('ans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzbioApp.answer')),
            ],
        ),
    ]
