# Generated by Django 3.2.5 on 2021-11-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzbioApp', '0002_alter_image_ans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ans_id',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzbioApp.answer'),
        ),
    ]
