# Generated by Django 3.2.5 on 2021-11-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzbioApp', '0003_alter_image_ans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
