# Generated by Django 3.2.5 on 2021-11-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzbioApp', '0004_alter_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
