# Generated by Django 3.2.5 on 2021-11-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzbioApp', '0006_alter_answer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ans_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
